name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
              sudo apt update
              sudo apt install -y build-essential cmake
              sudo apt install clang-format
              sudo apt install cmake-format

      - name: Configure project with CMake
        run: |
              cmake -S . -B build
